version: "1"
services:
  api-gateway:
    image: node:20.14-alpine
    ports:
      - "10601:10601"
    volumes:
      - ./api-gateway:/app
    working_dir: /app
    env_file:
      - api-gateway.env
    command: sh -c "npm install ; npx prisma generate; npx prisma migrate dev ; npm run prod"

  news-database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: news
    command: --port=4004
    ports:
      - 4004:4004

  user-database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "user"
    command: --port=4001
    ports:
      - 4001:4001

  asset-database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: asset
    command: --port=4002
    ports:
      - 4002:4002

  user-service:
    image: node:20.14-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./user-service:/app
    working_dir: /app
    env_file:
      - user.env
    command: sh -c "npm install ; npx prisma generate; npx prisma migrate dev ; npm run prod"

  asset-service:
    image: node:20.14-alpine
    ports:
      - "3002:3002"
    volumes:
      - ./asset-service:/app
    working_dir: /app
    env_file:
      - asset.env
    command: sh -c "npm install ; npx prisma generate; npx prisma migrate dev ; npm run prod"

  file-service:
    image: node:20.14-alpine
    ports:
      - "3003:3003"
    volumes:
      - ./file-service:/app
    working_dir: /app
    env_file:
      - file.env
    command: sh -c "npm install ; npm run prod"

  news-service:
    image: node:20.14-alpine
    ports:
      - "3004:3004"
    volumes:
      - ./news-service:/app
    working_dir: /app
    env_file:
      - news.env
    command: sh -c "npm install ; npx prisma generate; npx prisma migrate dev ; npm run prod"
